/* Lógico_1 — corrigido */

CREATE TYPE user_role   AS ENUM ('admin', 'teacher');
CREATE TYPE user_status AS ENUM ('invite_pending', 'active', 'inactive');

CREATE TABLE USERS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255),
    role user_role NOT NULL DEFAULT 'teacher',
    status user_status NOT NULL DEFAULT 'invite_pending',
    full_name varchar(255),
    school varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_email_lowercase
        CHECK (email = lower(email)),
    CONSTRAINT ck_users_active_requires_password
        CHECK (status <> 'active' OR password_hash IS NOT NULL)
);

CREATE TABLE INVITES (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE PASSWORD_RESET_TOKENS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE REFRESH_TOKENS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE EDUCATION_LEVELS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    sort_order smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE THEMES (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE BOOKS (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    author varchar(255) NOT NULL,
    synopsis text,
    isbn varchar(20) UNIQUE,
    page_count integer,
    edition varchar(50),
    cover_url text,
    store_url text,
    education_level_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_books_page_count_positive
        CHECK (page_count IS NULL OR page_count > 0)
);

CREATE TABLE INSTITUTIONAL_PAGES (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(80) NOT NULL UNIQUE,
    title varchar(160) NOT NULL,
    body text,
    external_url text,
    sort_order smallint NOT NULL DEFAULT 0,
    is_published boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_institutional_pages_has_content
        CHECK (body IS NOT NULL OR external_url IS NOT NULL)
);

CREATE TABLE ABORDA (
    FK_BOOKS_id bigint NOT NULL,
    FK_THEMES_id bigint NOT NULL,
    PRIMARY KEY (FK_BOOKS_id, FK_THEMES_id)
);

CREATE TABLE LECIONA (
    FK_USERS_id bigint NOT NULL,
    FK_THEMES_id bigint NOT NULL,
    PRIMARY KEY (FK_USERS_id, FK_THEMES_id)
);

CREATE TABLE ATENDE (
    FK_USERS_id bigint NOT NULL,
    FK_EDUCATION_LEVELS_id bigint NOT NULL,
    PRIMARY KEY (FK_USERS_id, FK_EDUCATION_LEVELS_id)
);

CREATE TABLE SELECIONA (
    FK_USERS_id bigint NOT NULL,
    FK_BOOKS_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (FK_USERS_id, FK_BOOKS_id)
);

/* US16: nome unico ignorando maiusculas/minusculas */
CREATE UNIQUE INDEX uq_themes_name_lower
    ON THEMES (lower(name));
CREATE UNIQUE INDEX uq_education_levels_name_lower
    ON EDUCATION_LEVELS (lower(name));

/* ---------- Chaves estrangeiras: 12, uma por relacionamento ---------- */

ALTER TABLE INVITES ADD CONSTRAINT FK_INVITES_1
    FOREIGN KEY (user_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_1
    FOREIGN KEY (user_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE REFRESH_TOKENS ADD CONSTRAINT FK_REFRESH_TOKENS_1
    FOREIGN KEY (user_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE BOOKS ADD CONSTRAINT FK_BOOKS_1
    FOREIGN KEY (education_level_id)
    REFERENCES EDUCATION_LEVELS (id)
    ON DELETE SET NULL;

ALTER TABLE ABORDA ADD CONSTRAINT FK_ABORDA_1
    FOREIGN KEY (FK_BOOKS_id)
    REFERENCES BOOKS (id)
    ON DELETE CASCADE;

ALTER TABLE ABORDA ADD CONSTRAINT FK_ABORDA_2
    FOREIGN KEY (FK_THEMES_id)
    REFERENCES THEMES (id)
    ON DELETE CASCADE;

ALTER TABLE LECIONA ADD CONSTRAINT FK_LECIONA_1
    FOREIGN KEY (FK_USERS_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE LECIONA ADD CONSTRAINT FK_LECIONA_2
    FOREIGN KEY (FK_THEMES_id)
    REFERENCES THEMES (id)
    ON DELETE CASCADE;

ALTER TABLE ATENDE ADD CONSTRAINT FK_ATENDE_1
    FOREIGN KEY (FK_USERS_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE ATENDE ADD CONSTRAINT FK_ATENDE_2
    FOREIGN KEY (FK_EDUCATION_LEVELS_id)
    REFERENCES EDUCATION_LEVELS (id)
    ON DELETE CASCADE;

ALTER TABLE SELECIONA ADD CONSTRAINT FK_SELECIONA_1
    FOREIGN KEY (FK_USERS_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

ALTER TABLE SELECIONA ADD CONSTRAINT FK_SELECIONA_2
    FOREIGN KEY (FK_BOOKS_id)
    REFERENCES BOOKS (id)
    ON DELETE CASCADE;
